name: Build and Publish PDF

on:
  push:
    paths:
      - '**.md'
      - 'template.tex'
      - '.github/workflows/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Install Pandoc, XeLaTeX, and fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-lang-bengali \
            fonts-noto-core \
            fonts-noto-mono \
            fonts-noto-unhinted

      - name: Sanitize Markdown input
        run: |
          iconv -f utf-8 -t utf-8 -c "Mobile Servicing Training.md" > clean.md

      - name: Convert Markdown to PDF using custom template
        run: |
          pandoc clean.md -o training_output.pdf \
            --pdf-engine=xelatex \
            --template=template.tex \
            -V mainfont="Noto Sans" \
            -V monofont="Noto Sans Mono" \
            -V CJKmainfont="Noto Serif Bengali" \
            -V fontsize=14pt

      - name: Copy PDF to output folder
        run: |
          mkdir -p public
          mv training_output.pdf public/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
